### ISSUE TITLE
Question about file in test suite

### ISSUE THREAD

**Issue by boxerab** [openpreserve/jpylyzer-test-files#2]
Dear BitsGalore,

I am trying to implement reading of xml box in my open source j2k codec.
I see that you have a file: null_terminated_content_in_xml_box.jp2 in your test suite.
Is this an edge case, or an error case?  Should the xml box NOT have null terminated content?

Thanks so much,
Aaron

**Comment by bitsgalore** [comment]
Hi Aaron,

This is an error case, see I.7.1 in the [JP2 spec](http://old.jpeg.org/public/15444-1annexi.pdf) which says the following about the DATA portion of XML boxes:

> DATA: This field shall contain a well-formed XML document as defined by REC-xml-19980210.

If there's a null terminator this will disqualify it as well-formed XML, and you will get a validation error in jpylyzer. 

From what I recall, there used to be some implementations that erroneously added a null character to the XML box, and this would raise an XML parse error jpylyzer. The `-nullxml` option was added to enable XML extraction for such cases.

**Comment by boxerab** [comment]
Thank you! That clears things up for me.
Aaron
