### ISSUE TITLE
Would you like some datasets compressed with ERDAS ECW/JP2 SDK?

### ISSUE THREAD

**Issue by VirtualTim** [openpreserve/jpylyzer-test-files#6]
I work for Hexagon Geospatial, so if it would help this project I could provide some JP's compressed with our SDK.
I see you have Kakadu compressed datasets, so I just thought hat maybe files compressed with an alternate compressor could be useful.

[Some more information from the official download site.](https://download.hexagongeospatial.com/downloads/ecw/erdas-ecw-jp2-sdk-v5-5-update-3-windows)

**Comment by bitsgalore** [comment]
@VirtualTim Yes, that would actually be really useful, thanks!

**Comment by VirtualTim** [comment]
I've attached some datasets that I think will be useful. I did this instead of creating a PR, as I wasn't really sure about things like naming conversions.

Here's why I included each dataset:
| Dataset | Reason |
| ------------- | ------------- |
| nullinput.uint8-rgb-null-2tileparts | null pattern (synthetic dataset) with:<br>&nbsp;&nbsp;max Lplt = 2^5-1<br>&nbsp;&nbsp;max plt's per tile-part = 2<br>This was created to be a small (for unit tests) dataset that's more representative of the larger datasets (>~4GB) the ERDAS APOLLO GeoCompressor can create. |
| sandiego3i_5.2 | Created with ECW JPEG 2000 SDK v5.2.0.172 |
| sandiego3i_5.5 | Created with ECW JPEG 2000 SDK v5.5.0.2042 (latest 2021 release) |
| sandiego1m_null.jp2 | Created with ECW JPEG 2000 SDK v3.5.0.4<br>Has "holes" to demonstrate alpha |

A lot of this is probably too much information, but I figured I'd let you decide what's superfluous.

[jpylyzer-test-files.zip](https://github.com/openpreserve/jpylyzer-test-files/files/6315246/jpylyzer-test-files.zip)

**Comment by VirtualTim** [comment]
Oh also nullinput.uint8-rgb-null-2tileparts has plt markers.

**Comment by bitsgalore** [comment]
@VirtualTim Hi Tim, I had completely forgotten about this, but I just added the files to the repo (with a 2.5 year delay!):

<https://github.com/openpreserve/jpylyzer-test-files/commit/c2676fd88ee4959283dd8fd29462f04c442fc301>

I also included them in the Jpylyzer unit tests.

Thanks again for making these images available!
