### ISSUE TITLE
Add High Throughput JPEG 2000 test images (JPH, JHC)

### ISSUE THREAD

**Issue by bitsgalore** [openpreserve/jpylyzer-test-files#9]

**Comment by bitsgalore** [comment]
Done:

<https://github.com/openpreserve/jpylyzer-test-files/commit/6a955ed5e079f7d19faec1d906b55b6515f83341>

**Comment by osamu620** [comment]
Hi @bitsgalore I believe osamu620/OpenHTJ2K#152 fixes this issue on OpenHTJ2K.

**Comment by bitsgalore** [comment]
Hi @osamu620 Yes, it does. I just updated the Jpylyzer test files repo accordingly:

<https://github.com/openpreserve/jpylyzer-test-files/commit/b21f6f611a671a519ddde0da30578a4df3a462f0>

Thanks again, great to see this fixed at such a short notice!

**Comment by osamu620** [comment]
@bitsgalore Thank you again for your findings. Those are very useful for creating more stable OpenHTJ2K and reference software.
